@startuml
'https://plantuml.com/use-case-diagram

package "Kontaktanfrage erstellen"{
"Nutzer\nsuchen" as (create)
"Kontaktanfrage\nsenden" as (send)
}
package "Kontaktanfrage erhalten"{
(Kontaktanfrage\nerhalten) as (receive)
(Kontaktanfrage\nannehmen oder ablehnen) as (decision)
}

Sender --> (create)
Sender --> (send)
(create) <. (send) :extend

Empfänger --> (receive)
Empfänger --> (decision)
(send) <... (receive) :extend
(receive) <. (decision) :extend

database "PostgreSQL DB" as DB
(decision) --> DB

@enduml