@startuml
skinparam classAttributeIconSize 0
hide empty members

database "PostgreSQL DB" as DB
actor Sender as SE
actor Empfänger as EM

package "Empfehlung geben"{
"Empfehlung\nerstellen" as (create)
"Empfehlung\nsenden" as (send)
}
package "Empfehlung erhalten"{
(Empfehlung\nerhalten) as (receive)
(Empfehlung\nspeichern) as (safe)
(Empfehlung\nablehnen) as (decline)
}
(Empfehlung\nansehen) as (lookup)

SE -u-> (create)
(create) <. (send) :extend
SE -> (send)

EM -> (receive)
(send) <... (receive) :extend
EM -> (safe)
DB -u-> (safe)
(receive) ..> (safe)
EM --> (decline)
(receive) ..> (decline)

EM -> (lookup)
DB -> (lookup)
(safe) <.. (lookup) :extend

@enduml