@startuml
'https://plantuml.com/use-case-diagram

package "Benutzerkonto anlegen"{
"Anmeldeformular\nausfüllen" as (create)
"Anmeldung\nabsenden" as (send)
}

Nutzer ---> (create)
(create) <. (send) :extend
Nutzer --> (send)

database "PostgreSQL DB" as DB
(send) --> DB

@enduml