@startuml
skinparam classAttributeIconSize 0
hide empty members

class User {
    - id : UUID
    - userName : String
    - displayName : String
    - email : String
    - password : String
    - imgId: Long
    + constructor()
    + getter()
    + setter()
}

class UserRepository {
    - user[] : User
    + findByEmailOrUserName(email: String, userName: String) : User
    + existsByEmail(email : String) : boolean
    + existsByUserName(userName : String) : boolean
    + save(user : User)
    + update(user : User)
    + delete(user : User)
}

class UserService {
    - userRepository : UserRepository
    + registerUser(user : User)
    + updateUser(user : User
    + deleteUser(user : User)
    + findByEmailOrUserName(input : String) : User
}

class UserController {
    - userService : UserService
    - authService : AuthService
    + GET /api/user/me() <<secured>>
    + GET /api/user/{id}() <<secured>>
    + GET /api/user/search() <<secured>>
    + POST /api/user/me()
    + PUT /api/user/me() <<secured>>
    + DELETE /api/user/me() <<secured>>
}

class JwtService {
    + generateToken(userName : String) : Token
    + extractUserName(token : Token) : String
}

class JwtAuthFilter {
    - jwtService : JwtService
    - authService : AuthService
    - userService : UserService
    # doFilterInternal()
}

note left of JwtAuthFilter
    Der JwtAuthFilter kontrolliert den
    Zugriff auf geschützte Endpunkte.
    Fehlt ein Token oder ist dieser
    ungültig, wird die Anfrage abgelehnt.
    Ein gültiger Token macht den User
    im Controller verfügbar.
end note

class AuthService {
    - jwtService : JwtService
    + login() : User
    + logout() : void
}

class AuthController {
    + POST /api/auth/login()
    + POST /api/auth/logout() <<secured>>
}

UserRepository --> User
UserService --> UserRepository
UserController --> AuthService
UserController --> UserService
AuthService --> JwtService
AuthController --> AuthService
JwtAuthFilter --> UserService
JwtAuthFilter --> JwtService
JwtAuthFilter --> AuthService

enum ContactStatus {
    PENDING
    ACCEPTED
    BLOCKED
}

class Contact {
    - id : UUID
    - status : ContactStatus
    - requester : User
    - receiver : User
    + constructor()
    + getter()
    + setter()
}

class ContactRepository {
    - contact[] : Contact
    + findAllByRequesterOrReceiverAndContactStatus(user : User) : Contact[]
    + findContactById(contactId : Long) : Contact
    + save(contact : Contact)
    + update(contact : Contact)
    + delete(contact : Contact)
}

class ContactService {
    - contactRepository : ContactRepository
    + getContactsByStatus(user : User, contactStatus : ContactStatus)
    + getContactById(contactId : Long)
    + createContact(user : User, receiverId : Long)
    + updateContactStatus(user : User, contactStatus : ContactStatus)
    + deleteContact(contactId : Long)
}

class ContactController {
    + GET /api/contact() <<secured>>
    + GET /api/contact/[id}() <<secured>>
    + POST /api/contact() <<secured>>
    + PUT /api/contact/{id}() <<secured>>
    + DELETE /api/contact/[id}() <<secured>>
}

Contact "0..*" --* "1" User
Contact ..> ContactStatus : <<use>>
ContactRepository --> Contact
ContactService --> ContactRepository
ContactController --> ContactService

class Recommendation {
    - id : UUID
    - title : String
    - description : String
    - imgPath : String
    - creator : User
    - creationDate : LocalDateTime
    - url : URI
    - rating : Int
    - category : Category
    - tags : Set<Tag>
    + constructor()
    + getter()
    + setter()
}
interface RecommendationRepository {
    - recommendations : Set<Recommendation>
    + findById(recommendationId : Long) : Recommendation
    + save(recommendation : Recommendation)
    + update(recommendation : Recommendation)
    + delete(recommendation : Recommendation)
}
class RecommendationService {
    - userService : UserService
    - recommendationRepository : RecommendationRepository
    - recommendationAssignmentRepository : RecommendationAssignmentRepository
    - categoryRepository : CategoryRepository
    - tagGroupRepository : TagGroupRepository
    - tagRepository : TagRepository
    + getRecommendationById(recommendationId : Long)
    + getRecommendationsByStatus(user : User, recommendationAssignmentStatus : RecommendationAssignmentStatus)
    + createRecommendation(user : User, requestBody : RequestBody)
    + createRecommendationAssignments(recommendation : Recommendation, receiver : Set<User>)
    + updateRecommendationStatus(user : User, recommendationAssignmentStatus : RecommendationAssignmentStatus)
}
class RecommendationController {
    + GET /api/recommendation() <<secured>>
    + GET /api/recommendation/{id}() <<secured>>
    + POST /api/recommendation() <<secured>>
    + PUT /api/recommendation/{id}() <<secured>>
}

class RecommendationAssignment {
    - userId : UUID
    - recommendationId : Long
    - recommendationAssignmentStatus : RecommendationAssignmentStatus
    + constructor()
    + getter()
    + setter()
}
interface RecommendationAssignmentRepository {
    - recommendationAssignments : Set<RecommendationAssignment>
    + findAllByUserAndStatus(user : User, status : RecommendationAssignmentStatus) : Set<RecommendationAssignment>
    + save(recommendationAssignment : RecommendationAssignment)
    + update(recommendationAssignment : RecommendationAssignment)
    + delete(recommendationAssignment : RecommendationAssignment)
}
enum RecommendationAssignmentStatus {
    SENT,
    ACCEPTED
}

class Category {
    - id : UUID
    - categoryType : CategoryType
    - tagGroups : List<TagGroup>
    + constructor()
    + getter()
    + setter()
}
interface CategoryRepository {
    - categories : Set<Category>
    + findByCategoryType(categoryType : CategoryType) : Category
    + save(category : Category)
    + update(category : Category)
    + delete(category : Category)
}
enum CategoryType {
    RECIPE,
    MEDIA,
    LOCATION,
    PRODUCT
}

class TagGroup {
    - id : UUID
    - tagGroupName : String
    - category : Category
    - tags : Set<Tag>
    + constructor()
    + getter()
    + setter()
}
interface TagGroupRepository {
    - tagGroups : Set<TagGroup>
    + findByCategory(category : Category) : TagGroup
    + findByTagGroupNameAndCategoryType(tagGroupName : String, categoryType : CategoryType) : TagGroup
    + save(tagGroup : TagGroup)
    + update(tagGroup : TagGroup)
    + delete(tagGroup : TagGroup)
}

class Tag {
    - id : UUID
    - tagName : String
    - tagGroup : TagGroup
    + constructor()
    + getter()
    + setter()
}
interface TagRepository {
    - tags : Set<Tag>
    + findByTagNameAndTagGroup(tagGroup : TagGroup, tagName : String) : Tag
    + save(tag : Tag)
    + update(tag : Tag)
    + delete(tag : Tag)
}
class TagService {
    - categoryRepository : CategoryRepository
    - tagGroupRepository : TagGroupRepository
    - tagRepository : TagRepository
    + getTagsByCategory(category : Category) : Set<Tag>
}
class TagController {
    + GET /api/tags() <<secured>>
}

Recommendation <-- RecommendationRepository
RecommendationRepository <-- RecommendationService
RecommendationService <-- RecommendationController

RecommendationAssignmentStatus <.. RecommendationAssignment
RecommendationAssignment <-- RecommendationAssignmentRepository
RecommendationAssignmentRepository <-- RecommendationService

CategoryType <.. Category
Category <-- CategoryRepository
CategoryRepository <-- RecommendationService
CategoryRepository <-- TagService

TagGroup <-- TagGroupRepository
TagGroupRepository <-- RecommendationService
TagGroupRepository <-- TagService

Tag <-- TagRepository
TagRepository <-- TagService
TagRepository <-- RecommendationService
TagService <-- TagController

UserService <-- RecommendationService

note left of RecommendationService
    Kommuniziert mit dem UserService
end note

note left of TagController
    Kann zukünftig, zum erstellen und bearbeiten der Kategorien,
    Tag-Gruppen und Tags, um Admin-Routes erweitert werden.
    Aktuell ist das erstellen durch einen Seed geplant.
end note

@enduml